#!/bin/sh

# Startup Applications

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
        . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
        . "$HOME/.xprofile"
fi

## If the device is a laptop and `Xmodmap` if Xmodmap exists load it
[ "$(hostnamectl chassis)" = "laptop" ] && [ -e $HOME/.config/x11/xmodmap ] && xmodmap $HOME/.config/x11/xmodmap 

## When using a your dumb keyboard can't change key maps
## Note that this also runs 'xmodmap ~/.Xmodmap'
# swapkeys

## Used to solve seahorse issues with custom xinitrc
## https://wiki.archlinux.org/title/GNOME/Keyring
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Relaunch DWM if the binary changes, otherwise bail
 csum=""
 new_csum=$(sha1sum $(which dwm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        ## Check if a dbus session is running
        if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
                logger "Starting dbus session"
                dbus-launch dwm
        else
                logger "dbus session has already been executed"
                exec dwm
        fi
    else
        exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
