#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your preferred software
DMENU="dmenu"
DMBROWSER="brave"
DMTERM="st -e"
DMEDITOR="${DMTERM} vim"

# dm-logout
logout_locker='slock'
# logout_locker='dm-tool lock'

# dm-bookman
bookman_show_source=1

# dm-sounds
sounds_dir="${HOME}/.config/dmscripts/dmsounds"

# dm-setbg
setbg_dir="${HOME}/Pictures/Wallpapers"

# dm-maim
maim_dir="${HOME}/Screenshots"
maim_file_prefix="maim"

# dm-confedit
confedit_editor="$DMEDITOR"
declare -A confedit_list
confedit_list[confedit]="$HOME/.config/dmscripts/config"
confedit_list[zsh]="$HOME/.config/zsh/.zshrc"
confedit_list[dunst]="$HOME/.config/dunst/dunstrc"
confedit_list[dwm]="$HOME/Code/Suckless/config.def.h"
confedit_list[dwmblocks]="$HOME/Code/Suckless/blocks.def.h"
confedit_list[neovim]="$HOME/.config/nvim/init.vim"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[st]="$HOME/Code/Suckless/config.def.h"
confedit_list[stumpwm]="$HOME/.config/stumpwm/config"
confedit_list[surf]="$HOME/Code/Suckless/config.def.h"
confedit_list[tabbed]="$HOME/Code/Suckless/config.def.h"
confedit_list[vifm]="$HOME/.config/vifm/vifmrc"
confedit_list[xinitrc]="$HOME/.xinitrc"
confedit_list[xresources]="$HOME/.Xresources"

# dm-reddit config
declare -a reddit_list=(
"r/archlinux"
"r/bash"
"r/commandline"
"r/freesoftware"
"r/linux"
"r/linux4noobs"
"r/linuxmasterrace"
"r/linuxquestions"
"r/suckless"
"r/Ubuntu"
"r/unixporn"
"r/vim"
)

# Search engine config
websearch_browser="$DMBROWSER"
declare -A websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Search Engines
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[gemini search \(https\)]="https://portal.mozz.us/gemini/geminispace.info/search%3F"
websearch[google]="https://www.google.com/search?q="
# Information/News
websearch[bbcnews]="https://www.bbc.co.uk/search?q="
websearch[cnn]="https://www.cnn.com/search?q="
websearch[googlenews]="https://news.google.com/search?q="
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
websearch[wiktionary]="https://en.wiktionary.org/w/index.php?search="
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[odysee]="https://odysee.com/$/search?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Online Shopping
websearch[amazon]="https://www.amazon.com/s?k="
websearch[craigslist]="https://www.craigslist.org/search/sss?query="
websearch[ebay]="https://www.ebay.com/sch/i.html?&_nkw="
websearch[gumtree]="https://www.gumtree.com/search?search_category=all&q="
# Linux
websearch[archaur]="https://aur.archlinux.org/packages/?O=0&K="
websearch[archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
websearch[debianpkg]="https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
# Development
websearch[github]="https://github.com/search?q="
websearch[gitlab]="https://gitlab.com/search?search="
websearch[googleOpenSource]="https://opensource.google/projects/search?q="
websearch[sourceforge]="https://sourceforge.net/directory/?q="
websearch[stackoverflow]="https://stackoverflow.com/search?q="
# Etc

# dm-youtube config
youtube_browser="mpv --script-opts=ytdl_hook-ytdl_path=yt-dlp"
# Think of these as your "subscribed channels", name the channel in the square brackets then put the channel URL in the quotation marks
# Syntax: youtube_channels[name]="https://www.youtube.com/link/to/channel"

declare -A youtube_channels
# Tech
youtube_channels[distrotube]="https://www.youtube.com/c/DistroTube/featured"
youtube_channels[brodie_robertson]="https://www.youtube.com/c/BrodieRobertson"

# Study
youtube_channels[infinitedrift]="https://www.youtube.com/@InfiniteDrift/videos"

# Fun
#
# dm-colpick config
declare -A colpick_list
colpick_list[black]="#282828"
colpick_list[red]="#cc241d"
colpick_list[green]="#98971a"
colpick_list[yellow]="#d79921"
colpick_list[blue]="#458588"
colpick_list[magenta]="#b16286"
colpick_list[cyan]="#689d6a"
colpick_list[white]="#ebdbb2"
colpick_list[orange]="#d65d0e"
colpick_list[purple]="#d3869b"

# dm-translate config
# Uncomment to manually set the languages dm-translate will show
# Get language codes from here: https://github.com/TheDavidDelta/lingva-translate/blob/main/utils/languages.json

# translate_list="manual"
# declare -A lang_map
# lang_map[Swedish]=sv
# lang_map[English]=en
# lang_map[Automatic]=auto

_revision=15
