#!/bin/bash

# Create the config directory if it does not exist
[ ! -d "~/.config/" ] && mkdir -p "~/.config"

# Define list of folders to 
conf_list=$(find . -maxdepth 1 -type d -not -name "." -not -name ".git")

for x in "${conf_list[@]}"; do
	#stow -t ~/ 
	echo $x
done


