#!/bin/sh
# stow -t ~/ alacritty
# stow -t ~/ compton
# stow -t ~/ doom
# stow -t ~/ gcalcli
# stow -t ~/ haros
# stow -t ~/ mailcap
# stow -t ~/ neomutt
# stow -t ~/ rofi
# stow -t ~/ sioyek
# stow -t ~/ spotifyd
# stow -t ~/ surf
# stow -t ~/ vifm
# stow -t ~/ xmobar
# stow -t ~/ xmonad
# sudo stow -t / ly
# stow -t ~/ aerc
# stow -t ~/ nvim
#stow -t ~/ Xmodmap

stow -t ~/ Xresources
stow -t ~/ aliasrc
stow -t ~/ authinfo
#stow -t ~/ davmail
stow -t ~/ dmscripts
stow -t ~/ dunst
#stow -t ~/ emacs
stow -t ~/ git
stow -t ~/ ncspot
stow -t ~/ newsboat
stow -t ~/ newsrc
stow -t ~/ octave
stow -t ~/ picom
#stow -t ~/ ranger
stow -t ~/ rustfmt
stow -t ~/ shortcutrc
stow -t ~/ xinitrc
stow -t ~/ zathura
stow -t ~/ zsh
stow -t ~/ zshenv
stow -t ~/ vim
stow -t ~/ tmux
#stow -t ~/ isync
